services:
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: graphcheck-prometheus
    restart: unless-stopped

    ports:
      - "9090:9090"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:12.1.0
    container_name: graphcheck-grafana
    restart: unless-stopped

    depends_on:
      - prometheus

    ports:
      - "3000:3000"

    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro

volumes:
  prometheus-data:
  grafana-data:
